---
# vim: set bs=2 sw=2 expandtab:
#
# configure and build Pentaho ETL validators
#
# Eric Belhomme <rico-github@ricozome.net> - 2018-07-22

- name: copy {{ etl_name }} files
  synchronize:
    src: "pentaho/{{ etl_name }}"
    dest: "{{ eor_tmp_install_path }}"

- name: copy the jdbc mysql connector to the jar
  copy:
    src: "{{ eor_mysql_connector_java_path }}"
    dest: "{{ eor_tmp_install_path }}/{{ etl_name }}/{{ eor_mysql_connector_java_path | basename }}"
    remote_src: yes

- name: ensure META-INF exists
  file:
    path: "{{ eor_tmp_install_path }}/{{ etl_name }}/META-INF"
    owner: "{{ wildfly.user }}"
    group: "{{ wildfly.group }}"
    state: directory
    mode: 0755

- name: put Manifest for {{ etl_name }}
  template:
    src: "pentaho/{{ etl_name }}/META-INF/MANIFEST.MF.j2"
    dest: "{{ eor_tmp_install_path }}/{{ etl_name }}/META-INF/MANIFEST.MF"

- name: put properties file for {{ etl_name }}
  template:
    src: "pentaho/{{ etl_name }}/{{ properties_name }}.properties.j2"
    dest: "{{ item }}/{{ properties_name }}.properties"
  with_items:
  - "{{ eor_tmp_install_path }}/{{ etl_name }}"
  - "{{ pentaho.path }}/validator"

- name: build JAR file {{ etl_name }}.jar
  archive:
    format: zip
    path: "{{ eor_tmp_install_path }}/{{ etl_name }}/*"
    dest: "{{ pentaho.path }}/validator/{{ etl_name }}.jar"
    owner: "{{ pentaho.user }}"
    group: "{{ pentaho.group }}"