---
# vim: set bs=2 sw=2 expandtab:
#
# System prerequisites
#
# Eric Belhomme <rico-github@ricozome.net> - 2018-07-22

- name: Disable SELinux
  selinux:
    state: disabled

- name: install EPEL repo
  yum:
    name: epel-release
    state: present

- name: install the 'eyesofnetwork-release' package
  yum:
    name: https://download.eyesofnetwork.com/repos/{{ eon_repo.version }}/base/eyesofnetwork-release-{{ eon_repo.version }}-{{ eon_repo.release }}.noarch.rpm
    state: present

- name: install package prerequisites
  yum:
    name: ['git', 'unzip', 'zip', 'bzip2', 'xz', 'rsync', 'httpd-tools','httpd', 'perl', 'net-tools', 'bind-utils', 'patch', 'dos2unix', 'firewalld', 'wget', 'libxslt', 'php-common', 'php-mysqlnd', 'php','php-xml', 'php-xmlrpc', 'php-ldap', 'mod_auth_eon', 'mariadb-server', 'expect', 'MySQL-python', 'docker', 'python-docker-py']
    state: present

- name: create dedicated group for EyesOfReport
  group:
    name: "{{ eor_group }}"
    state: present
    system: yes

- name: create dedicated user for EyesOfReport
  user:
    name: "{{ eor_owner }}"
    home: "{{ eor_install_path }}"
    comment: "Eyes Of Report dedicated user"
    group: "{{ eor_group }}"
    groups: apache
    system: yes
    create_home: no
    password_lock: yes

- name: "ensure firewalld server is running"
  systemd:
    name: firewalld
    state: started

- name: Set public zone as default policy
  command: firewall-cmd --set-default-zone=public

- name: "add firewalld rule for {{ item }} service"
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
  - ssh
  - snmp
  - http
  - https

- name: "add firewalld rule for MySQL"
  firewalld:
    port: "{{ tcp_ports.mysql[0] }}/tcp"
    permanent: true
    state: enabled

- name: "enable and start {{ item }} server"
  systemd:
    name: "{{ item }}"
    enabled: true
    state: restarted
  with_items:
  - firewalld
  - mariadb
  - docker

- name: clone eorweb Git repo
  git:
    repo: "{{ eorweb_git.repo }}"
    dest: "{{ eor_install_path }}/eorweb"
    version: "{{ eorweb_git.release }}"

- name: copy eorweb config.php sample file
  copy:
    remote_src: yes
    force: no
    src: "{{ eor_install_path }}/eorweb/include/config_sample.php"
    dest: "{{ eor_install_path }}/eorweb/include/config.php"

- name: ensure EOR archive directory exists
  file:
    path: "{{ eor_archive_path }}"
    state: directory
    owner: root
    group: "{{ eor_group }}"
    mode: 0750

- name: change timezone in php.ini
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: ";date.timezone ="
    line: "date.timezone = {{ item }}"
  with_items:
    - "{{ timezone }}"
