---
# vim: set bs=2 sw=2 expandtab:
#
# install & configure Oracle JRE 7u80 from local repo on
# RHEL & CentOS distros
#
# Eric Belhomme <rico-github@ricozome.net> - 2018-07-22

# Oracle's legacy JDKs are almost impossible to download automatically
# from Oracle website as it is mandatory to authenticate on Oracle's
# web portal.
# So you can either get the RPM from a local repo, or from a network fs
#
# See files/3rd_party/README.md to further details.
- name: get Oracle JDK package
  include_tasks: get_third_party_package.yml
  vars:
    package: "{{ pkg_jdk }}"

- name: install JRE package
  yum:
    name: "{{ eor_tmp_install_path }}/{{ pkg_jdk.uri | basename }}"
    state: present
  register: jdk_installed

# TODO: should be nice to deduce java path dynamically...
- block:
  - name: correct java version selected
    alternatives:
      name: java
      link: /usr/bin/java
      path: /usr/java/jdk1.7.0_80/bin/java

  - name: correct javac version selected
    alternatives:
      name: javac
      link: /usr/bin/javac
      path: /usr/java/jdk1.7.0_80/bin/javac

  - name: correct javaws version selected
    alternatives:
      name: javaws
      link: /usr/bin/javaws
      path: /usr/java/jdk1.7.0_80/bin/javaws

  when: jdk_installed.changed == true
  
#- name: delete JRE package installer
#  file:
#    path: /tmp/jdk-7u80-linux-x64.rpm
#    state: absent
