---
# vim: set bs=2 sw=2 expandtab:
#
# Install BIRT reporting java application
#
# Eric Belhomme <rico-github@ricozome.net> - 2018-07-22

- name: get BIRT package
  include_tasks: get_third_party_package.yml
  vars:
    package: "{{ pkg_birt }}"
    
- name: create temporary directory for birt runtime extraction
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ eor_tmp_install_path }}/birt/runtime"
  - "{{ eor_tmp_install_path }}/birt/war"

- name: uncompress Birt archive in a temporary directory
  unarchive:
    src: "{{ eor_tmp_install_path }}/{{ pkg_birt.uri | basename }}"
    dest: "{{ eor_tmp_install_path }}/birt/runtime"
    remote_src: yes

- name: find Birt WAR file
  find:
    paths: "{{ eor_tmp_install_path }}/birt/runtime"
    patterns: 'birt.war'
    recurse: yes
  register: find_war

- name: copy BIRT reports
  synchronize:
    src: "birt/report"
    dest: "{{ eor_install_path }}"
    owner: no
    perms: no

- name: set correct perms and ownership for reports
  file:
    dest: "{{ eor_install_path }}/report"
    owner: root
    group: "{{ eor_group }}"
    mode: u=rwX,g=rX
    recurse: yes

- block:

  - name: uncompress Birt WAR file in a temp dir
    unarchive:
      src: "{{ find_war.files[0].path }}"
      dest: "{{ eor_tmp_install_path }}/birt/war"
      remote_src: yes

  - name: copy MySQL java connector on Birt war
    copy:
      src: "{{ eor_mysql_connector_java_path }}"
      dest: "{{ eor_tmp_install_path }}/birt/war/WEB-INF/lib"
      remote_src: yes

  - name: copy bmrt.rptdesign template on Birt war
    template:
      src: birt/bmrt.rptdesign.j2
      dest: "{{ eor_tmp_install_path }}/birt/war/bmrt.rptdesign"

  - name: patch web.xml file on Birt war
    replace:
      dest: "{{ eor_tmp_install_path }}/birt/war/WEB-INF/web.xml"
      regexp: '(<param-name>BIRT_VIEWER_WORKING_FOLDER</param-name>\s*<param-value>).*(</param-value>)'
      replace: "\\1{{ eor_install_path }}/report/\\2"

  - name: compress patched birt WAR file
    archive:
      path: "{{ eor_tmp_install_path }}/birt/war/*"
      dest: "{{ wildfly.app_path }}/wildfly/standalone/deployments/birt.war"
      format: zip
      owner: "{{ wildfly.user }}"
      group: "{{ wildfly.group }}"
      mode: 0640
  when: find_war.matched == 1