---
# vim: set bs=2 sw=2 expandtab:
#
# Docker configuration
#
# The role first try to push a local Docker image archive from role's
# files/3rd_party directory.
#
# The file must follow the naming scheme:
#   docker.io_<image name>_<image tag>.tar.bz2
#
# This implies the docker image is bzip2 compressed.
#
# If it fails to find a local archive, it then download (pull) the image
# from official docker.io Hub repository.
#
# Eric Belhomme <rico-github@ricozome.net> - 2018-07-22

- name: ensure Docker is running
  systemd:
    name: docker
    state: started

- name: install CentOS docker image
  include_tasks: get_docker_image.yml
  vars:
    image_name: 'centos'
    image_tag: "{{ docker_image_centos }}"

- name: install Busybox docker image
  include_tasks: get_docker_image.yml
  vars:
    image_name: 'busybox'
    image_tag: "{{ docker_image_busybox }}"
