---
# vim: set bs=2 sw=2 expandtab:
#
# Docker configuration
#
# Eric Belhomme <rico-github@ricozome.net> - 2018-07-22

- name: install package prerequisites for Docker
  yum:
    name: "{{ item }}"
    state: present
  with_items:


- name: ensure Docker is running
  systemd:
    name: docker
    state: started

# todo: get docker images from docker.io
- name: unzip CentOS 7 docker container archive
  unarchive:
    src: "{{ eor_source_path }}/eyesofreport/CORE/dockers/centos_1503.zip"
    dest: "{{ eor_source_path }}/eyesofreport/CORE/dockers/"
    remote_src: yes

- name: Load CentOS Docker image from local archive
  docker_image:
    name: eor/centos
    tag: 7.1.1503
    load_path: "{{ eor_source_path }}/eyesofreport/CORE/dockers/centos_1503.tar"

- name: Load busybox Docker image from local archive
  docker_image:
    name: eor/busybox
    tag: latest
    load_path: "{{ eor_source_path }}/eyesofreport/CORE/dockers/busybox.tar"

