---
# vim: set bs=2 sw=2 expandtab:
#
# Install Wildfly application server
#
# Eric Belhomme <rico-github@ricozome.net> - 2018-07-22

- name: get Wildfly package
  include_tasks: get_third_party_package.yml
  vars:
    package: "{{ pkg_wildfly }}"

- name: create paths for Wildfly
  file:
    path: "{{ item }}"
    owner: "{{ wildfly.user }}"
    group: "{{ wildfly.group }}"
    state: directory
    mode: 0750
  with_items:
  - '/var/log/wildfly'
  - "{{ wildfly.report_path }}"
  - "{{ wildfly.app_path }}"

- name: uncompress Wildfly archive
  unarchive:
    src: "{{ eor_tmp_install_path }}/{{ pkg_wildfly.uri | basename }}"
    dest: "{{ wildfly.app_path }}"
    remote_src: yes

# TODO: deduce wildfly directory from the archive
- name: symlink wildfly current release
  file:
    path: "{{ wildfly.app_path }}/wildfly"
    src: "{{ wildfly.app_path }}/wildfly-9.0.2.Final"
    state: link
   
- name: install Wildfly systemd unit file
  template:
    src: wildfly/wildfly.service.j2
    dest: /etc/systemd/system/wildfly.service
    owner: root
    group: root
    mode: 0644
  register: install_wildfly_unit

- name: reload systemd configuration
  systemd:
    daemon_reload: yes
  when: install_wildfly_unit

- name: enable and start Wildfly service
  systemd:
    name: wildfly
    enabled: yes
    masked: no
    state: restarted

- name: put Wildfly CLI script on server
  template:
    src: wildfly/wildfly-configure.cli.j2
    dest: "{{ eor_tmp_install_path }}/wildfly-configure.cli"
    owner: root
    group: root
    mode: 0640

# as Wildfly takes a long time to start, the CLI might remain
# unreachable until it finishes to start. So let's have a try
# every 10s until it answers
- name: Configure Wildfly through CLI
  command: "{{ wildfly.app_path }}/wildfly/bin/jboss-cli.sh --connect --file={{ eor_tmp_install_path }}/wildfly-configure.cli"
  register: wildfly_cli
  until: wildfly_cli.rc == 0
  retries: 6
  delay: 10
  ignore_errors: yes
