---
# vim: set bs=2 sw=2 expandtab:
#
# tasks file for ansible-role-eyesofreport
#
# Eric Belhomme <rico-github@ricozome.net> - 2018-07-22

- name: fail execution if pwd variables are not overidden
  fail:
    msg: |
      "Error: you *MUST* define in your playbook custom passwords for the following variables:"
      sql_internal_pwd
      sql_external_pwd
      pentaho_pwd
  when: not sql_internal_pwd or not sql_external_pwd or not pentaho_pwd

- name: create temporary directory for installation purpose
  file:
    path: "{{ eor_tmp_install_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: system prerequisites
  include_tasks: install_system.yml
  tags:
  - prereqs

- name: install Oracle JDK
  include_tasks: install_jdk.yml
  tags:
  - java
  
- name: install & configure MariaDB and EOR databases
  include_tasks: install_mariadb.yml
  tags:
  - databases

- name: install & configure Docker
  include_tasks: install_docker.yml
  tags:
  - docker

- name: install & configure Pentaho ETL software
  include_tasks: install_pentaho.yml
  tags:
  - pentaho

- name: install & configure Wildfly application server
  include_tasks: install_wildfly.yml
  tags:
  - wildfly

- name: install & configure BIRT reporting webapp
  include_tasks: install_birt.yml
  tags:
  - birt

- name: install & configure HTTP server
  include_tasks: install_apache.yml
  tags:
  - web

- name: cleanup temporary installation dir
  file:
    path: "{{ eor_tmp_install_path }}"
    state: absent
  when: cleanup_install_files == true